use_frameworks!

target 'PodSpecsLibrary_Example' do
  pod 'PodSpecsLibrary', :path => '../'

  target 'PodSpecsLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
